// import './example/basic-type'
// let num: number = 123
// import './example/interface'
// import './example/function'
// import './example/generics'
// import './example/generics'
// import './example/es6-class.js'
// import './example/class'
// import './example/enum'
// import './example/interface-compablity'
// import './example/12.advanced-type1'
import './example/13.advanced-type2'
